
# https://kubernetes.io/blog/2018/01/introducing-client-go-version-6

# required = [
#   "k8s.io/code-generator/cmd/client-gen",
#   "k8s.io/code-generator/cmd/conversion-gen",
#   "k8s.io/code-generator/cmd/deepcopy-gen",
#   "k8s.io/code-generator/cmd/defaulter-gen",
#   "k8s.io/code-generator/cmd/informer-gen",
#   "k8s.io/code-generator/cmd/lister-gen",
# ]

# [[constraint]]
#   branch = "kubernetes-1.9.0"
#   name = "k8s.io/code-generator"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
name = "github.com/cloudflare/cloudflared"
source = "https://github.com/cloudflare/cloudflared.git"
revision = "148eea58997ed9a5a2e48b6ac0c671495c86e24a"