apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudflare-argo
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  - "extensions"
  resources:
  - ingresses
  - services
  - endpoints
  verbs:
  - list
  - get
  - watch
